import {products} from "@/lib/products";
const worlds=[["WOMEN","Strength. Ritual. Expression."],["MEN","Discipline. Form. Movement."],["ALL","No prescribed uniform."]];
export default function Home(){return <main>
<section className="hero"><div className="heroTop"><span>DROP 001 / AW26</span><span>GLASGOW — WORLDWIDE</span></div><div className="heroBody"><div className="eyebrow">FIND YOUR RELIGION®</div><h1>BUILD<br/>YOURSELF.</h1><p>Luxury athletics, self-care and everyday uniforms for sovereign individuals.</p><div className="heroActions"><a href="#shop">SHOP DROP 001</a><a href="#world">EXPLORE FYR</a></div></div><div className="scroll">SCROLL TO ENTER ↓</div></section>
<section className="ticker"><span>SELF CARE IS RITUAL</span><span>ATHLETICS IS DISCIPLINE</span><span>STYLE IS DECLARATION</span><span>NO PRESCRIBED PATH</span></section>
<section id="world" className="world"><div className="sectionHead"><span>SHOP YOUR WAY</span><span>FYR / WORLD 001</span></div><div className="worldGrid">{worlds.map((w,i)=><a className={"worldCard world"+i} href="#shop" key={w[0]}><span>0{i+1}</span><div><h2>{w[0]}</h2><p>{w[1]}</p><b>ENTER →</b></div></a>)}</div></section>
<section className="manifesto"><p>FIND YOUR RELIGION®</p><h2>There is no prescribed<br/>version of you.</h2><div className="manifestoCopy">Train the body. Care for it. Dress it deliberately. Build rituals that belong to you.</div></section>
<section id="shop" className="shop"><div className="sectionHead"><span>NEW / DROP 001</span><span>VIEW ALL →</span></div><div className="grid">{products.map((p,i)=><a href={"/product/"+p.slug} id={p.category.toLowerCase()} className="product" key={p.slug}><div className={"productImage tone"+(i%4)}><div className="productFlags"><span>{i<3?"NEW":"FYR SELECT"}</span><span>{p.category}</span></div><div className="silhouette"><i></i><i></i></div><button>QUICK ADD +</button></div><div className="productMeta"><div><h3>{p.name}</h3><small>{p.note} · MEN / WOMEN / ALL</small></div><strong>£{p.price}</strong></div></a>)}</div></section>
<section className="ritualFeature"><div className="ritualVisual"><span>RITUAL / 001</span><div className="orb"></div></div><div className="ritualCopy"><span>BODY / RECOVERY / CARE</span><h2>THE WORK<br/>CONTINUES<br/>AFTER TRAINING.</h2><p>Objects and essentials for recovery, preparation and daily practice.</p><a href="#shop">SHOP RITUAL →</a></div></section>
<section className="edition" id="editions"><span>FYR EDITIONS / MADE IN LIMITED NUMBERS</span><h2>Not everything<br/>should be mass made.</h2><p>Original FYR garments. Limited runs, considered materials, handmade and handwoven work.</p><button>DISCOVER EDITIONS →</button></section>
<section className="newsletter"><span>FYR PRIVATE LIST</span><h2>ENTER BEFORE<br/>EVERYONE ELSE.</h2><p>Early access to drops, editions and private releases.</p><form><input aria-label="Email" placeholder="YOUR EMAIL"/><button>JOIN →</button></form></section>
<section className="creed"><span>FIND YOUR RELIGION®</span><h2>THE SOVEREIGN INDIVIDUAL<br/>IS A WORK IN PROGRESS.</h2><p>BODY · RITUAL · UNIFORM · EDITIONS · OBJECTS</p></section></main>}