import {products} from "@/lib/products";
export default function Home(){const edit=products.slice(0,6);return <main className="house">
<section className="houseHero"><div className="houseHeroMeta"><span>FIND YOUR RELIGION®</span><span>GLASGOW / 2026</span></div><div className="houseFigure"><div className="figureHead"/><div className="figureBody"/></div><div className="houseTitle"><p>COLLECTION I</p><h1>Find your<br/><em>religion.</em></h1><div className="houseIntro">Original garments, selected objects and a private way to find what belongs to you.</div></div><a className="heroEnter" href="#collection">ENTER COLLECTION ↓</a></section>
<section className="houseStatement"><span>01</span><p>Not everything<br/>should be mass made.</p><small>Original FYR garments. Limited runs.<br/>Considered materials. Released when ready.</small></section>
<section className="houseCollection" id="collection"><div className="houseSectionTop"><span>THE EDIT</span><span>01 — 06</span></div><div className="editorialGrid">{edit.map((p,i)=><a href={"/product/"+p.slug} className={"editorialProduct ep"+i} key={p.slug}><div className="editorialImage"><div className="editorialForm"><i/><b/></div><span>{String(i+1).padStart(2,"0")}</span></div><div className="editorialMeta"><span>{p.name}</span><span>£{p.price}</span></div></a>)}</div><a className="quietLink" href="#private">VIEW COLLECTION →</a></section>
<section className="privateStyle" id="private"><div className="privateCopy"><span>PRIVATE STYLING</span><h2>Tell us what<br/>you are looking for.</h2><p>A dinner. A journey. A feeling. A budget. Start with a few words and FYR will build a personal edit around you—beginning with FYR, then looking further when it needs to.</p><a href="/stylist">BEGIN →</a></div><div className="privateInterface"><div className="privatePrompt">“Dinner in Paris.<br/>Black. Quiet.<br/>Nothing obvious.”</div><div className="privateResult"><span>YOUR EDIT</span><b>03 PIECES</b><small>FYR + SELECTED ELSEWHERE</small></div></div></section>
<section className="fitting"><div className="fittingVisual"><div className="fitHead"/><div className="fitBody"/><i>YOUR FORM</i></div><div className="fittingCopy"><span>THE FITTING ROOM / IN DEVELOPMENT</span><h2>One profile.<br/>Your proportions.<br/>Your wardrobe.</h2><p>Measurements, fit preferences and the choices you decide to save become a private reference for future selections.</p><a href="/stylist">ENTER PRIVATE STYLING →</a></div></section>
<section className="housePrivate"><span>PRIVATE RELEASES</span><h2>Released<br/><em>when ready.</em></h2><p>Small quantities. Selected pieces. No permanent calendar.</p><a href="#list">REQUEST ACCESS →</a></section>
<section className="houseList" id="list"><div><span>PRIVATE LIST</span><h2>Stay close.</h2></div><form><input aria-label="Email" placeholder="EMAIL ADDRESS"/><button>JOIN</button></form></section>
</main>}