import {products} from "@/lib/products";
const worlds=[["WOMEN","Movement. Ease. Expression."],["MEN","Form. Practice. Ease."],["LGBTQ","We identify as you identify."]];
const rituals=[["ROBES","Rest / Home / Recovery"],["CANDLES","Quiet / Atmosphere / Ritual"],["BODY","Exfoliation / Care / Touch"],["FRAGRANCE","Scent / Memory / Presence"],["SELF CARE","Kits / Objects / Daily ritual"],["AFRICAN VIBES","Textile / Culture / Expression"]];
export default function Home(){return <main>
<section className="hero"><div className="heroTop"><span>COLLECTION 001 / AW26</span><span>GLASGOW — WORLDWIDE</span></div><div className="heroBody"><div className="eyebrow">FIND YOUR RELIGION®</div><h1>FIND YOUR<br/>VIBE.</h1><p>Clothing, movement, scent and daily ritual. Made for a life considered.</p><div className="heroActions"><a href="#shop">COLLECTION 001</a><a href="#world">EXPLORE</a></div></div><div className="scroll">FIND YOUR RELIGION ↓</div></section>
<section className="ticker"><span>FIND YOUR VIBE</span><span>FIND YOUR RITUAL</span><span>FIND YOUR FORM</span><span>FIND YOUR RELIGION</span></section>
<section id="world" className="world"><div className="sectionHead"><span>WE IDENTIFY AS YOU IDENTIFY</span><span>FYR / 001</span></div><div className="worldGrid">{worlds.map((w,i)=><a className={"worldCard world"+i} href="#shop" key={w[0]}><span>0{i+1}</span><div><h2>{w[0]}</h2><p>{w[1]}</p><b>VIEW →</b></div></a>)}</div></section>
<section className="concierge" id="concierge"><div className="conciergeIntro"><span>FYR / CONCIERGE</span><h2>FIND WHAT<br/>FEELS LIKE YOU.</h2><p>Shop by mood, ritual, moment or budget. FYR Concierge will shape a considered selection around what you ask for.</p><div className="conciergePrompts"><span>“A quiet Sunday at home.”</span><span>“Build a recovery ritual under £180.”</span><span>“Earth tones. African Vibes. Something easy.”</span></div><button>FIND MY VIBE →</button><small>CONCIERGE PREVIEW · PERSONAL SHOPPING COMING SOON</small></div><div className="vibeCard"><div className="vibeTop"><span>YOUR RITUAL / 01</span><span>£164</span></div><h3>SUNDAY<br/>QUIET.</h3><div className="vibeItems"><span>RITUAL ROBE</span><span>BODY EXFOLIATION</span><span>FYR CANDLE</span><span>SCENT SAMPLE</span></div><button>BUILD THIS RITUAL →</button></div></section>
<section className="accountStrip"><div><span>YOUR FYR</span><h3>One account. Your sizes, saved rituals, orders, preferences and private releases.</h3></div><div className="accountActions"><button>CREATE ACCOUNT</button><button>CONNECT WALLET</button></div></section>
<section className="manifesto"><p>FIND YOUR RELIGION®</p><h2>There is no prescribed<br/>version of you.</h2><div className="manifestoCopy">Find your pace. Find your scent. Find your people. Find your quiet. Find your vibe. Find your religion.</div></section>
<section id="shop" className="shop"><div className="sectionHead"><span>COLLECTION 001</span><span>VIEW ALL →</span></div><div className="grid">{products.map((p,i)=><a href={"/product/"+p.slug} id={p.category.toLowerCase()} className="product" key={p.slug}><div className={"productImage tone"+(i%4)}><div className="productFlags"><span>{i<3?"NEW":"FYR SELECT"}</span><span>{p.category}</span></div><div className="silhouette"><i></i><i></i></div><button>VIEW +</button></div><div className="productMeta"><div><h3>{p.name}</h3><small>{p.note}</small></div><strong>£{p.price}</strong></div></a>)}</div></section>
<section className="ritualFeature"><div className="ritualVisual"><span>RITUAL / 001</span><div className="orb"></div></div><div className="ritualCopy"><span>BODY / HOME / SCENT / CARE</span><h2>YOUR RITUAL,<br/>YOUR WAY.</h2><p>Robes, candles, body care, fragrance and objects for the quieter parts of the day.</p><a href="#rituals">EXPLORE RITUAL →</a></div></section>
<section className="ritualIndex" id="rituals"><div className="sectionHead"><span>FYR / RITUALS</span><span>FOR BODY + SPACE</span></div><div className="ritualIndexGrid">{rituals.map((r,i)=><a href="#private-list" className="ritualIndexItem" key={r[0]}><span>0{i+1}</span><h3>{r[0]}</h3><p>{r[1]}</p></a>)}</div></section>
<section className="edition" id="editions"><span>FYR EDITIONS / LIMITED</span><h2>Not everything<br/>should be mass made.</h2><p>Original FYR garments. Limited runs, considered materials, handmade and handwoven work.</p><button>VIEW EDITIONS →</button></section>
<section className="africanEdition"><span>FYR / AFRICAN VIBES</span><h2>ROOTED.<br/>REIMAGINED.</h2><p>Textile, form and expression informed by African craft, movement and culture. Small runs. Considered collaborations.</p><a href="#private-list">DISCOVER →</a></section>
<section className="founderRelease" id="private-releases"><div className="founderReleaseNo">FYR / PRIVATE 001</div><div className="founderReleaseBody"><span>PRIVATE RELEASE</span><h2>RELEASED<br/>WHEN READY.</h2><p>Selected pieces made in small numbers and released without a permanent calendar.</p><div className="releaseMeta"><span>LIMITED</span><span>PRIVATE LIST ACCESS</span><span>SELECTED RELEASES</span></div><a href="#private-list">PRIVATE LIST →</a></div></section>
<section className="checkoutStory"><span>FYR / CHECKOUT</span><h2>YOUR WAY<br/>TO PAY.</h2><p>Checkout is being designed for card, Apple Pay, Google Pay and supported crypto payments. Wallet connection will also support FYR identity and selected private access.</p><div className="payMethods"><span>CARD</span><span>APPLE PAY</span><span>GOOGLE PAY</span><span>CRYPTO</span><span>WALLET</span></div><small>PAYMENT OPTIONS SHOWN AS PRODUCT DIRECTION · NOT YET LIVE</small></section>
<section className="newsletter" id="private-list"><span>FYR PRIVATE LIST</span><h2>FIND YOUR<br/>VIBE.</h2><p>Early notice of editions, rituals, selected releases and collaborations.</p><form><input aria-label="Email" placeholder="YOUR EMAIL"/><button>JOIN →</button></form></section>
<section className="creed"><span>FIND YOUR RELIGION®</span><h2>IDENTIFY AS YOU IDENTIFY.</h2><p>BODY · RITUAL · SCENT · FORM · REST · CULTURE · EDITIONS</p></section></main>}